name: Flask Ngrok Preview

on:
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyngrok

    - name: Set FLASK_APP environment variable
      run: echo "FLASK_APP=app.py" >> $GITHUB_ENV

    - name: Set up Ngrok auth token
      run: |
        echo "from pyngrok import ngrok
ngrok.set_auth_token('${{ secrets.NGROK_AUTHTOKEN }}')" > set_token.py
        python set_token.py

    - name: Start Flask in background
      run: |
        nohup flask run --host=0.0.0.0 --port=5000 &

    - name: Expose with Ngrok for 120 seconds
      run: |
        echo "from pyngrok import ngrok
import time
url = ngrok.connect(5000)
print('🔗 URL ngrok:', url)
time.sleep(120)" > expose.py
        python expose.py
